name: "Install Approov CLI"
description: "Install the Approov CLI in a GitHub Actions build environment"
author: "Brandon McAnsh"
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'yellow'
